LIBS=
CFLAGS=-Wall -pedantic -std=c99
LDFLAGS= -static ${LIBS}

# builds x, the test runner & runs the test(s)
all: x test

install:
	@echo "no installation required nor needed"

# remove test runner, autogenerated header file & obj-files
clean:
	-rm -f test_x test_x_mu.h *.o

# Example -> x.c
x.o: x.h

x: x.o
	$(CC) ${CFLAGS} $< -o $@

.c.o:
	$(CC) ${CFLAGS} -c $< -o $@

#  x's test runner
test: test_x
	./test_x

# generate test_x_mu.h file, to be #include'd in 'test_x.c'
test_x_mu.h: test_x.c
	./mu_header test_x

# strip main from x, the test runner provides 'main'
test_x: minunit.h test_x_mu.h test_x.o x.o
	strip -N main x.o -o x_stripped.o
	${CC} ${CFLAGS} test_x.o x_stripped.o -o $@
